export const timeline = [
  {
    company: "Moglix",
    title: "Web Developer",
    date: "Sep 2022 - Present",
    description: "Building the future of e-commerce",
    responsibilities: [
      "Worked on 5 projects Maas, Credlix (Nuphi and Exim), EOC, and DIGIMRO.",
      "Updated Angular version from 7 to 12 and enabled strict mode.",
      "Implemented Invoice Breakup, Payment Breakup, Credit Notes, and Debit Notes with angular material design.",
      "Login and Signup for supplier and admin with angular material design.",
      "Implemented lazy loading, reducing initial load time by 30% for large modules and components.",
      "Utilized Webpack for code splitting and bundling, minimizing application bundle size.",
      "Optimized API calls through batching and caching, improving data retrieval times by 40%.",
      "Configured Angular Router to handle complex routing scenarios, including nested routes, route guards, and parameterized routes for dynamic navigation.",
      "Utilized Angular services for business logic and data sharing across components, adhering to the service-oriented architecture principle.",
      "Created custom directives and pipes to extend the HTML capabilities and to format data dynamically within templates.",
      "Implemented global error handling mechanisms and logging services to enhance the application's robustness and ease of maintenance.",
      "Configured HTTP interceptors for handling authentication, logging, and error handling for HTTP requests.",
      "Applied security best practices, including route guards, JWT authentication, and secure HTTP headers to safeguard the application.",
      "Integrated RESTful APIs using Angular’s HTTPClientModule to communicate with backend services efficiently.",
    ],
  },
  {
    company: "Cogitate Technology Solutions",
    title: "Associate Developer",
    date: "Apr 2022 - Sep 2022",
    description: "Building the future of Digital Insurance Technology",
    responsibilities: [
      "Implemented Vehicle Info with angular material design.",
      "Implemented Driver Info with angular material design.",
      "Implemented Policy Info with angular material design.",
    ],
  },
  {
    company: "DataRitz Technologies",
    title: "Full Stack Development Intern",
    date: "May 2021 - Oct 2021",
    description: "Building the future of social networking",
    responsibilities: [
      "Developed a new feature that improves the user experience",
      "Implemented a recommendation algorithm to suggest friends",
      "Enhanced the news feed algorithm to show more relevant posts",
      "Built a feature for tracking user activity",
    ],
  },
  {
    company: "DataRitz Technologies",
    title: "Machine Learning Intern",
    date: "2019 - 2020",
    description: "Building the future of technology",
    responsibilities: [
      "Improved the iOS operating system to enhance user experience",
      "Developed a new feature that personalizes user interface",
      "Enhanced the app store algorithm to suggest more relevant apps",
      "Implemented a feature for tracking app usage",
    ],
  },
  {
    company: "ABES Engineering College",
    title: "Python 3 technology Intern",
    date: "Jun 2019 - Jul 2019",
    description: "Building the future of software",
    responsibilities: [
      "Improved the Windows operating system to enhance user experience",
      "Developed a new feature that personalizes user interface",
      "Enhanced the office suite to improve productivity",
      "Implemented a feature for tracking software usage",
    ],
  },
];
