export const timeline = [
  {
    company: "Moglix",
    title: "Web Developer",
    date: "Sep 2022 - Present",
    description: "Building the future of e-commerce",
    responsibilities: [
      "Worked on 5 projects Maas, Credlix (Nuphi and Exim), EOC, and DIGIMRO.",
      "Updated Angular version from 7 to 12 and enabled strict mode.",
      "Implemented Invoice Breakup, Payment Breakup, Credit Notes, and Debit Notes with angular material design.",
      "Login and Signup for supplier and admin with angular material design.",
      "Implemented lazy loading, reducing initial load time by 30% for large modules and components.",
      "Utilized Webpack for code splitting and bundling, minimizing application bundle size.",
      "Optimized API calls through batching and caching, improving data retrieval times by 40%.",
      "Configured Angular Router to handle complex routing scenarios, including nested routes, route guards, and parameterized routes for dynamic navigation.",
      "Utilized Angular services for business logic and data sharing across components, adhering to the service-oriented architecture principle.",
      "Created custom directives and pipes to extend the HTML capabilities and to format data dynamically within templates.",
      "Implemented global error handling mechanisms and logging services to enhance the application's robustness and ease of maintenance.",
      "Configured HTTP interceptors for handling authentication, logging, and error handling for HTTP requests.",
      "Applied security best practices, including route guards, JWT authentication, and secure HTTP headers to safeguard the application.",
      "Integrated RESTful APIs using Angular’s HTTPClientModule to communicate with backend services efficiently.",
    ],
  },
  {
    company: "Cogitate Technology Solutions",
    title: "Associate Developer",
    date: "Apr 2022 - Sep 2022",
    description: "Building the future of Digital Insurance Technology",
    responsibilities: [
      "Spearheaded the development of a comprehensive digital insurance platform, transforming traditional insurance processes into efficient, cloud-native solutions.",
      "Designed and developed a vehicle information module using Angular Material, ensuring a responsive and user-friendly interface.",
      "Utilized reactive forms and validation to enhance user experience and data accuracy.",
      "Created a driver information component with Angular Material, providing a seamless and interactive user interface.",
      "Integrated RESTful services to fetch and display driver data, ensuring real-time updates and synchronization.",
      "Developed a policy information module with Angular Material, focusing on an intuitive and accessible design.",
      "Implemented complex form handling and validation, supporting a wide range of policy data inputs.",
      "Structured the application using a modular architecture, enhancing code reusability, maintainability, and scalability.",
      "Configured Angular Router for advanced routing scenarios, including nested routes, lazy loading, and route guards.",
      "Ensured the application’s responsiveness and cross-browser compatibility using Angular Material and custom CSS.",
    ],
  },
  {
    company: "DataRitz Technologies",
    title: "Full Stack Development Intern",
    date: "May 2021 - Oct 2021",
    description: "Building the future of emotions detection techniques",
    responsibilities: [
      "Acquired and applied knowledge in HTML, CSS, JavaScript, Bootstrap, jQuery, and MySQL to develop EmoScript.",
      "Created EmoScript, a comprehensive emotion detection platform utilizing both Facial Recognition and Speech Recognition.",
      "Implemented real-time emotion detection using live video feed, leveraging advanced facial recognition algorithms.",
      "Enabled emotion analysis from pre-recorded videos, supporting various video formats for user convenience.",
      "Developed functionality to detect emotions from uploaded images, ensuring accurate facial expression analysis.",
      "Integrated speech recognition technology to analyze and detect emotions from uploaded audio files.",
      "Implemented natural language processing (NLP) techniques to analyze and identify emotions in text input.",
      "Designed a user-friendly and intuitive interface using Bootstrap, ensuring accessibility and ease of use across different devices.",
      "Enhanced user interaction with jQuery, creating dynamic and responsive UI elements.",
      "Applied various optimization techniques to ensure real-time processing and quick response times for emotion detection tasks.",
    ],
  },
  {
    company: "DataRitz Technologies",
    title: "Machine Learning Intern",
    date: "2019 - 2020",
    description: "Building the future of heart disease prediction technology",
    responsibilities: [
      "Built a machine learning system to predict the likelihood of heart disease in individuals using various ML algorithms.",
      "Collected and processed a CSV dataset containing multiple health parameters to train the model.",
      "Trained the model on historical health data to ensure accurate predictions.",
      "Validated the model's performance using test datasets to ensure reliability.",
      "Designed the system to output results in a simple boolean format: '0' indicating the presence of heart disease, and '1' indicating the absence.",
      "Documented the development process and findings, providing clear and concise reports on the project’s progress and outcomes.",
    ],
  },
  {
    company: "ABES Engineering College",
    title: "Python 3 technology Intern",
    date: "Jun 2019 - Jul 2019",
    description: "Learned Python and its libraries",
    responsibilities: [
      "Built various Python applications to solve real-world problems, enhancing practical programming skills.",
      "Conducted data analysis and created visualizations using libraries like Pandas and Matplotlib, improving data interpretation skills.",
      "Automated repetitive tasks with Python scripts, increasing efficiency and productivity.",
      "Worked in a team to complete projects, fostering collaboration and teamwork.",
    ],
  },
];
